import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

test('database-free accounts, atomic rewards, persistence, origins, admin and logout',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'ecoverse-test-'));
 process.env.DATA_FILE=join(directory,'state.json');process.env.NODE_ENV='development';
 const {default:app}=await import('../server/app.js');
 const {changeStore}=await import('../server/store.js');
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 const base=`http://127.0.0.1:${server.address().port}/api`;let cookie='';
 const request=async(path,method='GET',body,origin='http://localhost:3001')=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return {status:response.status,...await response.json()}};
 try{
 assert.equal((await request('/health')).data.databaseRequired,false);
 assert.equal((await request('/user/progress')).status,401);
 assert.equal((await request('/auth/register','POST',{},'https://untrusted.example')).status,403);
 const credentials={name:'Test Member',email:'member@example.test',password:'Long-test-password-123'};
 const registered=await request('/auth/register','POST',credentials);assert.equal(registered.status,201);const id=registered.data.id;assert.equal(registered.data.password_hash,undefined);
 assert.equal((await request('/auth/register','POST',credentials)).status,409);
 assert.equal((await request('/auth/me')).data.name,'Test Member');
 const catalog=(await request('/challenges')).data;assert.equal(catalog.length,12);
 assert.equal((await request('/challenges/1/complete','POST',{points:999})).status,400);
 const attempts=await Promise.all([request('/challenges/1/complete','POST',{},'http://localhost:5173'),request('/challenges/1/complete','POST',{},'http://127.0.0.1:3001')]);assert.deepEqual(attempts.map(x=>x.status).sort(),[201,409]);
 const state=(await request('/user/progress')).data;assert.equal(state.ecoPoints,20);assert.equal(state.challengesCompleted,1);assert.equal(state.badges[0].id,'first-seed');
 const saved=JSON.parse(await readFile(process.env.DATA_FILE,'utf8'));assert.equal(saved.transactions.length,1);assert.notEqual(saved.users[0].password_hash,credentials.password);
 for(const period of ['global','weekly','monthly'])assert.equal((await request('/leaderboard?period='+period)).data[0].points,20);
 assert.equal((await request('/user/impact')).data.categories[0].actions,1);
 assert.equal((await request('/admin/stats')).status,403);
 await changeStore(data=>{data.users[0].role='admin';data.completions[0].completion_day='2020-01-01';return true});
 assert.equal((await request('/admin/stats')).status,200);
 const draft={title:'New challenge',description:'A test challenge description.',category:'water',difficulty:'Easy',points:10,is_active:true};
 const created=await request('/admin/challenges','POST',draft);assert.equal(created.status,201);
 assert.equal((await request('/admin/challenges/'+created.data.id,'PATCH',{...draft,is_active:false})).status,200);
 assert.equal((await request('/challenges/'+created.data.id)).status,404);
 assert.equal((await request('/challenges/1/complete','POST',{})).status,201);
 assert.equal((await request('/user/progress')).data.ecoPoints,40);
 const goal=await request('/user/goals','POST',{title:'Keep <growing>',category:'waste',target:1,deadline:new Date().toISOString().slice(0,10)});assert.equal(goal.status,201);assert.equal(goal.data.status,'completed');
 assert.equal((await request('/user/goals','POST',{title:'Impossible date',category:'all',target:1,deadline:'2026-02-31'})).status,400);
 const beforePurchase=(await request('/user/progress')).data;
 const purchases=await Promise.all([request('/user/shop/fern/buy','POST',{}),request('/user/shop/fern/buy','POST',{})]);assert.deepEqual(purchases.map(r=>r.status).sort(),[201,409]);
 const afterPurchase=(await request('/user/progress')).data;assert.equal(afterPurchase.ecoPoints,beforePurchase.ecoPoints);assert.equal(afterPurchase.forestLevel,beforePurchase.forestLevel);assert.equal(afterPurchase.spendablePoints,beforePurchase.ecoPoints-20);
 assert.equal((await request('/user/shop/lantern/buy','POST',{})).status,409);
 assert.equal((await request('/user/forest/layout','PUT',{placements:[{item_id:'lantern',slot:0}]})).status,403);
 assert.equal((await request('/user/forest/layout','PUT',{placements:[{item_id:'fern',slot:0}]})).status,200);
 assert.equal((await request('/user/shop')).data.placements[0].slot,0);
 const journal=(await request('/user/journal')).data,entryId=journal[0].id;
 const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jS1kAAAAASUVORK5CYII=';
 assert.equal((await request('/user/journal/'+entryId,'PUT',{note:'Used my refill bottle.',photo})).status,200);
 assert.equal((await request('/user/journal')).data[0].note,'Used my refill bottle.');
 assert.equal((await request('/user/journal/'+entryId,'PUT',{note:'Invalid',photo:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);
 for(const challengeId of [2,3,4,5])assert.equal((await request('/challenges/'+challengeId+'/complete','POST',{})).status,201);
 assert.equal((await request('/user/journey')).data.quests.find(q=>q.id==='balanced').progress,3);
 const claims=await Promise.all([request('/user/quests/balanced/claim','POST',{}),request('/user/quests/balanced/claim','POST',{})]);assert.deepEqual(claims.map(r=>r.status).sort(),[200,409]);
 assert.equal((await request('/user/quests/three-days/claim','POST',{})).status,409);
 const report=await fetch(base+'/user/report',{headers:{Cookie:cookie}});assert.equal(report.status,200);assert.match(report.headers.get('content-disposition'),/attachment/);const html=await report.text();assert.ok(html.includes('Keep &lt;growing&gt;'));assert.ok(!html.includes('password_hash'));
 const originalCookie=cookie;cookie='';const other=await request('/auth/register','POST',{name:'Other member',email:'other@example.test',password:'Other-long-password'});assert.equal(other.status,201);
 assert.equal((await request('/user/journal/'+entryId,'PUT',{note:'Cross-user change',photo:null})).status,404);
 assert.equal((await request('/user/goals/'+goal.data.id,'DELETE',{})).status,404);
 cookie=originalCookie;
 assert.equal((await request('/auth/logout','POST',{})).status,200);
 assert.equal((await request('/auth/me')).status,401);
 assert.equal((await request('/auth/login','POST',{email:credentials.email,password:'wrong-password'})).status,401);
 assert.equal((await request('/auth/login','POST',credentials)).status,200);
 assert.equal((await request('/user/forest')).data.ecoPoints,155);
 const {streaks,weekStart}=await import('../server/features.js');
 const days=['2026-09-04','2026-09-05','2026-09-05','2026-09-06'].map(completion_day=>({completion_day}));
 assert.deepEqual(streaks(days,'2026-09-07'),{current:3,longest:3,activeDays:3,activeToday:false});
 assert.equal(streaks(days,'2026-09-08').current,0);assert.equal(weekStart('2026-09-06'),'2026-08-31');assert.equal(weekStart('2026-09-07'),'2026-09-07');
 }finally{await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true})}
});
