const rows = [
  [
    "recycle",
    "Recycle Today",
    "Sort clean paper, metal, and accepted plastics into your local recycling.",
    "waste",
    "Easy",
    20,
  ],
  [
    "energy",
    "Energy Saver",
    "Switch off unused lights and unplug idle devices today.",
    "energy",
    "Easy",
    15,
  ],
  [
    "commute",
    "Green Commute",
    "Replace one car journey with walking, cycling, or public transport.",
    "transport",
    "Medium",
    30,
  ],
  [
    "water",
    "Save Water",
    "Take a shower under five minutes and turn off taps while brushing.",
    "water",
    "Easy",
    20,
  ],
  [
    "plant",
    "Plant Something",
    "Plant or care for a native tree, herb, or pollinator-friendly plant.",
    "lifestyle",
    "Bold",
    50,
  ],
  [
    "plastic",
    "Reduce Plastic",
    "Use reusable bags and containers instead of single-use plastic today.",
    "waste",
    "Medium",
    25,
  ],
  [
    "cold-wash",
    "Cold Wash",
    "Run a full laundry load on a cold cycle.",
    "energy",
    "Easy",
    15,
  ],
  [
    "meal",
    "Plant-based Meal",
    "Prepare a plant-based meal with seasonal ingredients.",
    "lifestyle",
    "Medium",
    35,
  ],
  [
    "refill",
    "Refill, Reuse",
    "Refill your reusable bottle instead of buying bottled water.",
    "water",
    "Easy",
    10,
  ],
  [
    "food",
    "No Food Left Behind",
    "Use leftovers or ingredients that would otherwise go to waste.",
    "waste",
    "Easy",
    20,
  ],
  [
    "repair",
    "Repair & Keep",
    "Repair, mend, or maintain an item instead of replacing it.",
    "lifestyle",
    "Bold",
    40,
  ],
  [
    "walk",
    "Walk the Last Mile",
    "Walk a short errand that you would normally drive.",
    "transport",
    "Easy",
    20,
  ],
];
export const challenges=rows.map(([slug,title,description,category,difficulty,points],i)=>({id:i+1,slug,title,description,category,difficulty,points,icon:'leaf',is_active:true}));
