const rows = [
  [
    "recycle",
    "Recycle Today",
    "Sort clean paper, metal, and accepted plastics into your local recycling.",
    "waste",
    "Easy",
    20,
  ],
  [
    "energy",
    "Energy Saver",
    "Switch off unused lights and unplug idle devices today.",
    "energy",
    "Easy",
    15,
  ],
  [
    "commute",
    "Green Commute",
    "Replace one car journey with walking, cycling, or public transport.",
    "transport",
    "Medium",
    30,
  ],
  [
    "water",
    "Save Water",
    "Take a shower under five minutes and turn off taps while brushing.",
    "water",
    "Easy",
    20,
  ],
  [
    "plant",
    "Plant Something",
    "Plant or care for a native tree, herb, or pollinator-friendly plant.",
    "lifestyle",
    "Bold",
    50,
  ],
  [
    "plastic",
    "Reduce Plastic",
    "Use reusable bags and containers instead of single-use plastic today.",
    "waste",
    "Medium",
    25,
  ],
  [
    "cold-wash",
    "Cold Wash",
    "Run a full laundry load on a cold cycle.",
    "energy",
    "Easy",
    15,
  ],
  [
    "meal",
    "Plant-based Meal",
    "Prepare a plant-based meal with seasonal ingredients.",
    "lifestyle",
    "Medium",
    35,
  ],
  [
    "refill",
    "Refill, Reuse",
    "Refill your reusable bottle instead of buying bottled water.",
    "water",
    "Easy",
    10,
  ],
  [
    "food",
    "No Food Left Behind",
    "Use leftovers or ingredients that would otherwise go to waste.",
    "waste",
    "Easy",
    20,
  ],
  [
    "repair",
    "Repair & Keep",
    "Repair, mend, or maintain an item instead of replacing it.",
    "lifestyle",
    "Bold",
    40,
  ],
  [
    "walk",
    "Walk the Last Mile",
    "Walk a short errand that you would normally drive.",
    "transport",
    "Easy",
    20,
  ],
  ["air-dry", "Air-Dry a Load", "Dry suitable laundry on a line or rack instead of using a dryer.", "energy", "Easy", 20],
  ["thermostat", "Adjust the Thermostat", "Use a moderate energy-saving temperature setting for part of your day.", "energy", "Medium", 25],
  ["leak-check", "Check for Water Leaks", "Inspect accessible taps and fixtures for visible drips or leaks.", "water", "Easy", 25],
  ["bucket-rinse", "Wash Without a Running Tap", "Use a filled basin for a suitable cleaning task instead of continuous running water.", "water", "Medium", 20],
  ["compost", "Start a Compost Batch", "Add suitable food scraps to a home or community compost system.", "waste", "Medium", 30],
  ["e-waste", "Route E-Waste Responsibly", "Take an unwanted electronic item to an authorized collection point.", "waste", "Bold", 35],
  ["carpool", "Share the Journey", "Carpool for a journey that would otherwise require separate vehicles.", "transport", "Medium", 30],
  ["transit-plan", "Use Public Transport", "Complete a practical journey by bus, train, tram, or shared transit.", "transport", "Medium", 25],
  ["habitat-cleanup", "Clean a Local Habitat", "Safely collect litter from a permitted local green space.", "nature", "Bold", 40],
  ["pollinator-water", "Create a Pollinator Water Stop", "Set up a shallow, safe water source with landing stones for insects.", "nature", "Medium", 25],
  ["borrow", "Borrow Before Buying", "Borrow or share an item you only need temporarily instead of purchasing it.", "lifestyle", "Easy", 25],
  ["meat-free-day", "Complete a Meat-Free Day", "Choose balanced plant-based meals for one complete day.", "lifestyle", "Bold", 40],
];
const guidance = {
  recycle: [
    "Keep reusable materials in circulation and out of mixed waste.",
    "Check local recycling rules. Separate accepted materials, rinse where needed, and use the correct collection.",
    "Photograph the sorted materials before collection. Do not include private documents.",
    "10 minutes",
  ],
  energy: [
    "Avoid wasting electricity when equipment is not needed.",
    "Identify idle devices, switch them off safely, and describe what changed. Never touch wiring.",
    "Show the switched-off devices and explain your routine. A photo alone cannot measure saved electricity.",
    "10 minutes",
  ],
  commute: [
    "Replacing car trips can reduce transport emissions.",
    "Choose a safe walking, cycling, or public transport route for a journey you would otherwise drive.",
    "Photograph your bicycle, transit ticket with personal details hidden, or destination. Explain the replaced trip.",
    "One journey",
  ],
  water: [
    "Conserving freshwater also reduces the energy needed to treat and move it.",
    "Choose a safe water-saving habit and describe how you applied it.",
    "Show a timer or water-saving setup. Never upload intimate bathroom photos.",
    "5–10 minutes",
  ],
  plant: [
    "Appropriate native plants provide food and shelter for local species.",
    "Choose a locally suitable plant, plant it with permission, water it, and plan ongoing care.",
    "Show the planted item and describe where and how you will care for it.",
    "30 minutes",
  ],
  plastic: [
    "Reusing items reduces demand for disposable packaging.",
    "Take reusable bags and containers to replace single-use items during a real errand.",
    "Show the reusable items in use, without other people’s faces.",
    "One errand",
  ],
  "cold-wash": [
    "Cold washing can reduce the energy used for water heating.",
    "Check garment care instructions and wash a full suitable load on a cold cycle.",
    "Show the cycle setting and explain the load. Do not photograph private clothing.",
    "One wash",
  ],
  meal: [
    "Food choices can support less resource-intensive routines.",
    "Prepare a balanced plant-based meal using ingredients available to you.",
    "Show the finished meal and describe the ingredients.",
    "30 minutes",
  ],
  refill: [
    "A durable refillable bottle can replace disposable bottles.",
    "Safely refill your bottle from a drinking-water source during your day.",
    "Show your bottle at the refill point and explain what purchase it replaced.",
    "5 minutes",
  ],
  food: [
    "Using edible leftovers helps prevent avoidable food waste.",
    "Check food safety first, then prepare a meal with ingredients that would otherwise be discarded.",
    "Show the meal and explain which leftovers you used.",
    "20 minutes",
  ],
  repair: [
    "Keeping products in use reduces demand for replacement materials.",
    "Choose a safe repair within your skills. Avoid electrical or structural repairs without expertise.",
    "Show the repaired item and describe the change.",
    "30–60 minutes",
  ],
  "air-dry": [
    "Air drying avoids the energy used by a tumble dryer.",
    "Check care labels, then safely hang a suitable washed load on a rack or line.",
    "Show the drying setup and describe what you did not machine-dry. Keep private clothing out of view.",
    "10 minutes setup",
  ],
  thermostat: [
    "Moderate heating and cooling settings can reduce avoidable energy use.",
    "With household permission, choose a safe moderate setting for part of the day.",
    "Show the control without revealing an address or identifiers, and describe the duration.",
    "Two hours",
  ],
  "leak-check": [
    "Finding visible leaks early can prevent continuing water loss.",
    "Inspect only accessible fixtures. Report problems rather than attempting unsafe plumbing work.",
    "Show the inspected fixture and explain what you checked. Never photograph private activity.",
    "10 minutes",
  ],
  "bucket-rinse": [
    "Using a fixed amount of water can prevent a tap running throughout a task.",
    "Fill a basin or bucket with only what you need, then turn the tap off.",
    "Show the prepared water and describe the task without including people.",
    "15 minutes",
  ],
  compost: [
    "Composting can return suitable organic material to soil instead of mixed waste.",
    "Check your compost rules, then add only accepted plant-based scraps.",
    "Show the accepted scraps before adding them and identify the compost method.",
    "10 minutes",
  ],
  "e-waste": [
    "Authorized collection keeps electronics and batteries out of ordinary waste streams.",
    "Remove personal data and use a manufacturer, retailer, or municipal collection service.",
    "Show the item at collection or a receipt with personal details hidden.",
    "One drop-off",
  ],
  carpool: [
    "Sharing an occupied vehicle can avoid an additional separate journey.",
    "Coordinate a safe shared trip and follow local road-safety rules.",
    "Show a non-identifying journey detail and explain which trip was avoided. Ask before photographing people.",
    "One journey",
  ],
  "transit-plan": [
    "Public transport can replace an individual car journey where suitable service exists.",
    "Plan and complete a safe route using an available transit service.",
    "Show a ticket or station detail with names and account details hidden.",
    "One journey",
  ],
  "habitat-cleanup": [
    "Removing litter can reduce hazards for wildlife in a shared green space.",
    "Work with permission, wear gloves, avoid hazardous waste, and dispose of collected material correctly.",
    "Show the area before and the safely bagged litter afterward. Do not disturb wildlife.",
    "20-40 minutes",
  ],
  "pollinator-water": [
    "A shallow water stop can help insects during hot or dry conditions.",
    "Use a shallow clean dish, add stable landing stones, and keep it away from pesticides and pets.",
    "Show the setup and describe how often you will clean and refill it.",
    "10 minutes",
  ],
  borrow: [
    "Sharing occasional-use items can reduce unnecessary purchases.",
    "Borrow with clear permission and agree on a return plan.",
    "Show the item without exposing another person or private messages, and explain what purchase it replaced.",
    "One borrowed item",
  ],
  "meat-free-day": [
    "A day of varied plant-based meals can introduce lower-impact food routines.",
    "Plan balanced meals suited to your dietary needs and restrictions.",
    "Show the meals or ingredients and briefly describe breakfast, lunch, and dinner.",
    "One day",
  ],
  walk: [
    "Short car journeys can sometimes be replaced with an active trip.",
    "Pick a safe nearby errand and walk instead of driving.",
    "Show a safe destination detail and describe the errand; do not expose your home address.",
    "15–30 minutes",
  ],
};
export const challenges = rows.map(
  ([slug, title, description, category, difficulty, points], i) => ({
    id: i + 1,
    slug,
    title,
    description,
    category: slug === "plant" ? "nature" : category,
    difficulty,
    points,
    icon: "leaf",
    is_active: true,
    benefit: guidance[slug][0],
    instructions: guidance[slug][1],
    proof_requirements: guidance[slug][2],
    estimated_time: guidance[slug][3],
  }),
);
