CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(256) NOT NULL, avatar VARCHAR(500), role ENUM('user','admin') NOT NULL DEFAULT 'user',
 eco_score INT NOT NULL DEFAULT 0, eco_points INT NOT NULL DEFAULT 0, trust_score INT NOT NULL DEFAULT 50, public_forest BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS challenges (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(80) NOT NULL UNIQUE, title VARCHAR(100) NOT NULL,
 description VARCHAR(500) NOT NULL, category VARCHAR(20) NOT NULL, difficulty VARCHAR(20) NOT NULL,
 points INT UNSIGNED NOT NULL, icon VARCHAR(20) NOT NULL DEFAULT 'leaf', is_active BOOLEAN DEFAULT TRUE,
 benefit TEXT, instructions TEXT, proof_requirements TEXT, estimated_time VARCHAR(80), proof_required BOOLEAN NOT NULL DEFAULT TRUE,
 impact_type VARCHAR(40), impact_value DECIMAL(10,3), impact_unit VARCHAR(30), impact_note VARCHAR(500),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS challenge_completions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, challenge_id INT UNSIGNED NOT NULL,
 completion_day DATE NOT NULL, completed_at TIMESTAMP NULL, status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
 proof_url VARCHAR(255), description TEXT, location VARCHAR(200), submitted_at TIMESTAMP NULL,
 reviewed_at TIMESTAMP NULL, reviewed_by INT UNSIGNED, rejection_reason VARCHAR(500),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, points_snapshot INT UNSIGNED NOT NULL DEFAULT 0,
 proof_required BOOLEAN NOT NULL DEFAULT TRUE, proof_hash CHAR(64), review_flags VARCHAR(500),
 impact_type VARCHAR(40), impact_value DECIMAL(10,3), impact_unit VARCHAR(30), impact_note VARCHAR(500),
 UNIQUE KEY once_per_day(user_id,challenge_id,completion_day),
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(challenge_id) REFERENCES challenges(id),
 FOREIGN KEY(reviewed_by) REFERENCES users(id), INDEX review_queue(status,submitted_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS point_transactions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, points INT NOT NULL,
 type VARCHAR(40) NOT NULL, reference_id INT UNSIGNED UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(reference_id) REFERENCES challenge_completions(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS forest_progress (
 user_id INT UNSIGNED PRIMARY KEY, forest_level INT NOT NULL DEFAULT 1, growth_points INT NOT NULL DEFAULT 0,
 trees_unlocked INT NOT NULL DEFAULT 0, wildlife_unlocked INT NOT NULL DEFAULT 0,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS badges (
 id VARCHAR(50) PRIMARY KEY, name VARCHAR(80) NOT NULL, description VARCHAR(255) NOT NULL,
 requirement_type VARCHAR(30), requirement_value INT, icon VARCHAR(30) DEFAULT 'leaf', kind VARCHAR(20) NOT NULL DEFAULT 'verified'
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_badges (
 user_id INT UNSIGNED NOT NULL, badge_id VARCHAR(50) NOT NULL, earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 legacy BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(user_id,badge_id), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(badge_id) REFERENCES badges(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS submission_reviews (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, completion_id INT UNSIGNED NOT NULL, reviewer_id INT UNSIGNED NOT NULL,
 decision ENUM('APPROVED','REJECTED') NOT NULL, reason VARCHAR(500), trust_delta INT NOT NULL,
 proof_url VARCHAR(255), description TEXT, location VARCHAR(200), reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(completion_id) REFERENCES challenge_completions(id), FOREIGN KEY(reviewer_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS sessions (
 session_id VARCHAR(128) PRIMARY KEY, expires INT UNSIGNED NOT NULL, data MEDIUMTEXT NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_extras (
 user_id INT UNSIGNED PRIMARY KEY, payload JSON NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quiz_results (
 user_id INT UNSIGNED NOT NULL, topic VARCHAR(30) NOT NULL, score INT NOT NULL, completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,topic), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(80) PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS campaigns (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100) NOT NULL, description VARCHAR(500) NOT NULL,
 starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, badge_id VARCHAR(50), is_active BOOLEAN NOT NULL DEFAULT TRUE,
 FOREIGN KEY(badge_id) REFERENCES badges(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS campaign_challenges (
 campaign_id INT UNSIGNED NOT NULL, challenge_id INT UNSIGNED NOT NULL, PRIMARY KEY(campaign_id,challenge_id),
 FOREIGN KEY(campaign_id) REFERENCES campaigns(id), FOREIGN KEY(challenge_id) REFERENCES challenges(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS teams (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, join_code CHAR(8) NOT NULL UNIQUE,
 owner_id INT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(owner_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS team_members (
 team_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL UNIQUE, joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(team_id,user_id), FOREIGN KEY(team_id) REFERENCES teams(id), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS community_posts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, completion_id INT UNSIGNED NOT NULL UNIQUE, user_id INT UNSIGNED NOT NULL,
 caption VARCHAR(500), share_photo BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(completion_id) REFERENCES challenge_completions(id), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS post_reactions (
 post_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,kind ENUM('inspired','cheer') NOT NULL,
 PRIMARY KEY(post_id,user_id),FOREIGN KEY(post_id) REFERENCES community_posts(id),FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS post_comments (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,body VARCHAR(500) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(post_id) REFERENCES community_posts(id),FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL,title VARCHAR(120) NOT NULL,
 message VARCHAR(500) NOT NULL,link VARCHAR(255),read_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id),INDEX notification_feed(user_id,read_at,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS review_assignments (
 completion_id INT UNSIGNED PRIMARY KEY,reviewer_id INT UNSIGNED NOT NULL,assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(completion_id) REFERENCES challenge_completions(id),FOREIGN KEY(reviewer_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_reset_tokens (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,used_at DATETIME NULL,FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
